name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalar dependencias
        run: yarn install
      - name: Compilar acción
        run: yarn build
      - name: Ejecutar pruebas E2E
        run: yarn test:e2e
