name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependencias
        run: yarn install
      - name: Verificar estilo de código
        run: yarn lint
      - name: Verificar formato Prettier
        run: yarn prettier --check .
