name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'   # se activa cuando se crea un tag como v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: yarn install --frozen-lockfile

      - name: Compilar TypeScript
        run: yarn build  # genera la carpeta dist/

      - name: Crear paquete para release
        run: |
          mkdir -p release
          cp -r dist/ release/
          cp action.yml release/

      - name: Publicar release en GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
